[2023-03-03T15:04:40.297+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_dag.load_data manual__2023-03-03T15:04:34.618953+00:00 [queued]>
[2023-03-03T15:04:40.307+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: ETL_dag.load_data manual__2023-03-03T15:04:34.618953+00:00 [queued]>
[2023-03-03T15:04:40.308+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T15:04:40.308+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-03T15:04:40.308+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T15:04:40.325+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data> on 2023-03-03 15:04:34.618953+00:00
[2023-03-03T15:04:40.334+0000] {standard_task_runner.py:55} INFO - Started process 10045 to run task
[2023-03-03T15:04:40.337+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_dag', 'load_data', 'manual__2023-03-03T15:04:34.618953+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ETL_dag.py', '--cfg-path', '/tmp/tmpzh18y8fg']
[2023-03-03T15:04:40.339+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask load_data
[2023-03-03T15:04:40.411+0000] {task_command.py:388} INFO - Running <TaskInstance: ETL_dag.load_data manual__2023-03-03T15:04:34.618953+00:00 [running]> on host bb703684ec8f
[2023-03-03T15:04:40.497+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=ETL_dag
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T15:04:34.618953+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T15:04:34.618953+00:00
[2023-03-03T15:04:40.499+0000] {postgres.py:158} INFO - Running copy expert: COPY bitcoin_data FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_data.csv
[2023-03-03T15:04:40.510+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-03-03T15:04:40.514+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_dag.py", line 40, in _store_data
    filename='/tmp/processed_data.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 166, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.NumericValueOutOfRange: value "1675267200000" is out of range for type integer
CONTEXT:  COPY bitcoin_data, line 1, column time: "1675267200000"

[2023-03-03T15:04:40.525+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_dag, task_id=load_data, execution_date=20230303T150434, start_date=20230303T150440, end_date=20230303T150440
[2023-03-03T15:04:40.539+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 37 for task load_data (value "1675267200000" is out of range for type integer
CONTEXT:  COPY bitcoin_data, line 1, column time: "1675267200000"
; 10045)
[2023-03-03T15:04:40.589+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-03T15:04:40.610+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
